Forcing virtual box provider. Restarting etcd on reboot.

diff --git a/desktop b/desktop
--- a/desktop
+++ b/desktop
@@ -33,12 +33,12 @@ echo_help="help:          Show this help"
 function displayLogo {
     tput clear
     echo ""
-    echo -e "\033[30;90m███████╗ ██████╗  █████████╗ ██████╗ \033[0m\033[30;31m ██████████╗ ██████╗  ██╗  ██╗\033[0m"
-    echo -e "\033[30;90m██╔══██║  ╚═══██╗ ███╗  ███║  ╚═══██╗\033[0m\033[30;31m ██║ ██╔ ██║  ╚═══██╗ ╚██╗██╔╝\033[0m"
-    echo -e "\033[30;90m██   ██║ ███████║ ███║  ███║ ███████║\033[0m\033[30;31m ██║╚██║ ██║ ███████║  ╚███╔╝ \033[0m"
-    echo -e "\033[30;90m███████╝ ███████║ ███║  ███║ ███████║\033[0m\033[30;31m ██║╚██║ ██║ ███████║  ██╔██╗ \033[0m"
-    echo -e "\033[30;90m██║      ███████║ ███║  ███║ ███████║\033[0m\033[30;31m ██║╚██║ ██║ ███████║ ██╔╝ ██╗\033[0m"
-    echo -e "\033[30;90m╚═╝      ╚══════╝ ╚══╝  ╚══╝ ╚══════╝\033[0m\033[30;31m ╚═╝ ╚═╝ ╚═╝ ╚══════╝ ╚═╝  ╚═╝\033[0m"
+    echo -e "\033[1;90;40m███████╗ ██████╗  █████████╗ ██████╗ \033[0m\033[31;40m ██████████╗ ██████╗  ██╗  ██╗\033[0m"
+    echo -e "\033[1;90;40m██╔══██║  ╚═══██╗ ███╗  ███║  ╚═══██╗\033[0m\033[31;40m ██║ ██╔ ██║  ╚═══██╗ ╚██╗██╔╝\033[0m"
+    echo -e "\033[1;90;40m██   ██║ ███████║ ███║  ███║ ███████║\033[0m\033[31;40m ██║╚██║ ██║ ███████║  ╚███╔╝ \033[0m"
+    echo -e "\033[1;90;40m███████╝ ███████║ ███║  ███║ ███████║\033[0m\033[31;40m ██║╚██║ ██║ ███████║  ██╔██╗ \033[0m"
+    echo -e "\033[1;90;40m██║      ███████║ ███║  ███║ ███████║\033[0m\033[31;40m ██║╚██║ ██║ ███████║ ██╔╝ ██╗\033[0m"
+    echo -e "\033[1;90;40m╚═╝      ╚══════╝ ╚══╝  ╚══╝ ╚══════╝\033[0m\033[31;40m ╚═╝ ╚═╝ ╚═╝ ╚══════╝ ╚═╝  ╚═╝\033[0m"
     echo ""
     echo "CenturyLink Labs - http://www.centurylinklabs.com/"
 }
@@ -301,7 +301,7 @@ function createPmxVM {
         echo "Error downloading images disk. Please try again later."
         exit 1;
     fi
-    runVagrant up || { echo "VM Creation failed. Exiting."; exit 1; }
+    runVagrant up --provider virtualbox || { echo "VM Creation failed. Exiting."; exit 1; }
     rm -f $IMAGES_ZIP
 }
 
