Adding update

diff --git a/desktop b/desktop
--- a/desktop
+++ b/desktop
@@ -3,7 +3,7 @@
 PANAMAX_PORT_UI=8888
 PANAMAX_PORT_API=8889
 BASEBOX=coreos-alpha
-VERSION=stable
+IMAGE_TAG_DEFAULT=stable
 pmxUiTags="http://74.201.240.198:5000/v1/repositories/panamax-ui/tags"
 pmxApiTags="http://74.201.240.198:5000/v1/repositories/panamax-api/tags"
 setupUpdateUrl="http://63.128.180.11/installer/"
@@ -12,12 +12,12 @@ function checkPreReqs {
     echo ""
     echo "Checking if required software is installed."
     echo ""
-    
+
     vagrant -v | grep "1.5" 2>&1 >/dev/null
     if [[ "$?" -ne "0" ]]; then
 	    echo "Please install vagrant version 1.5 or newer (https://www.vagrantup.com/downloads.html).";
 	    exit 1;
-    else 
+    else
 	    echo $'Vagrant 1.5 or newer installed.'
     fi
 
@@ -25,7 +25,7 @@ function checkPreReqs {
     if [[ "$?" -ne "0" ]]; then
         echo "Please install Virtualbox (https://www.virtualbox.org/wiki/Downloads).";
         exit 1;
-    else 
+    else
     	echo $'Virtualbox 4.2 or newer installed.'
     fi
     echo ""
@@ -81,7 +81,7 @@ function checkForPanamaxUpdate {
        updateAvailableForPmx="0"
        if [[ -f .env ]]; then
         source .env
-        if [[ "$INSTALL_VERSION" == "dev" ]]; then
+        if [[ "$IMAGE_TAG" == "dev" ]]; then
             if [[ "$INSTALL_DATE" -le "` date -j -v-1d +%s`" ]]; then
                 echo "You are currently running a Dev version of Panamax which is updated nightly."
                 echo "A newer Dev version is available. Use the update option to get the latest Dev version."
@@ -131,35 +131,36 @@ function installPanamax {
         echo ""
         read -p "Enter default UI port($PANAMAX_PORT_UI):"  panamaxPortUi
         read -p "Enter default API port($PANAMAX_PORT_API):"  panamaxPortApi
-        read -p "Enter version you want to use(dev/stable, defaults to:$VERSION):" panamaxVersion
+        read -p "Enter version you want to use(dev/stable, defaults to:$IMAGE_TAG_DEFAULT)" panamaxVersion
         echo ""
-    fi 
-    
+    fi
+
     panamaxPortUi=${panamaxPortUi:-$PANAMAX_PORT_UI}
     panamaxPortApi=${panamaxPortApi:-$PANAMAX_PORT_API}
     redownload=${download:-N}
-    panamaxVersion=${panamaxVersion:-$VERSION}
+    IMAGE_TAG=${panamaxVersion:-${IMAGE_TAG:-$IMAGE_TAG_DEFAULT}}
 
     echo export PANAMAX_PORT_UI=$panamaxPortUi > .env
     echo export PANAMAX_PORT_API=$panamaxPortApi >> .env
     echo export BASEBOX=$BASEBOX >> .env
     echo export SETUP_VERSION=\"$(<.version)\" >> .env
-    echo export INSTALL_VERSION=$panamaxVersion >> .env
     echo export INSTALL_DATE=\"`date +%s`\" >> .env
-    if [[ "$panamaxVersion" == "stable" ]]; then
+    if [[ "$IMAGE_TAG" == "stable" ]]; then
         echo export INSTALL_TAG_UI=\"$(getLatestTagUi)\" >> .env
         echo export INSTALL_TAG_API=\"$(getLatestTagApi)\" >> .env
     fi
+    setEnvVar "IMAGE_TAG" "$IMAGE_TAG"
+    setEnvVar "OPERATION" "$operation"
     source .env
 
-    if [[  $operation == "reinstall" ]]; then 
+    if [[  $operation == "reinstall" ]]; then
         echo ""
         echo "Reinstalling the vagrant machine"
-	if [[ "$#" == "0" ]]; then 
+	if [[ "$#" == "0" ]]; then
 	    read -p "Would you like to re-download coreos base box(N): " redownload
 	fi
         vagrant destroy -f || { "VM Destroy failed. Exiting." exit 1; }
-        if [[ $redownload == "Y" ]]; then 
+        if [[ $redownload == "Y" ]]; then
             vagrant box update --box $BASEBOX || { "Vagrant box remove failed. Exiting." exit 1; }
         else
         vagrant up || { "VM Creation failed. Exiting." exit 1; }
@@ -168,9 +169,14 @@ function installPanamax {
 	echo ""
 	echo "Creating a new vagrant machine"
 	vagrant up || { "VM Creation failed. Exiting." exit 1; }
-    fi  
-            
+    fi
+
     openPanamax;
+}
+
+function setEnvVar {
+    echo $"`sed  "/$1/d" .env`" > .env
+    echo export $1=$2 >> .env
 }
 
 function openPanamax {
@@ -180,7 +186,7 @@ function openPanamax {
       printf .
       sleep 2
     done
-   
+
     echo ""
     open "http://localhost:$PANAMAX_PORT_UI" || { echo "Please goto http://localhost:$PANAMAX_PORT_UI"; }
     echo ""
@@ -189,6 +195,7 @@ function openPanamax {
 
 function restartPanamax {
     echo Restarting Panamax
+    setEnvVar "OPERATION" "$operation"
     source .env
     vagrant reload || { echo >&2 "Restarting Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
     openPanamax;
@@ -198,21 +205,32 @@ function restartPanamax {
 
 function stopPanamax {
     echo Stopping Panamax
+    setEnvVar "OPERATION" "$operation"
     source .env
     vagrant halt || { echo >&2 "Stopping Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
     echo Panamax stopped.
 }
 
+function updatePanamax {
+    setEnvVar "OPERATION" "$operation"
+    setEnvVar "IMAGE_TAG" "$IMAGE_TAG"
+    source .env
+    echo Updating Panamax
+    vagrant reload --provision || { echo >&2 "Updating Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
+    openPanamax;
+    echo Update Complete
+}
 function uninstallPanamax {
+  setEnvVar "OPERATION" "$operation"
   echo Uninstalling Panamax
   vagrant box remove $BASEBOX
   vagrant destroy -f
-  echo Uninstall complete. 
+  echo Uninstall complete.
 }
 
 function showHelp {
     echo ""
-    echo "Usage: 
+    echo "Usage:
 	 ./desktop install/-op=install [-ppUi=<panamax UI port>] [-ppApi=<panamax API port>]
 	 ./desktop reinstall/-op=reinstall [-ppUi=<panamax UI port>] [-ppApi=<panamax API port>]
 	 ./desktop restart/-op=restart
@@ -230,10 +248,10 @@ function readParams {
     do
     case $i in
         --dev)
-        panamaxVersion=dev
+        IMAGE_TAG=dev
         ;;
         --stable)
-        panamaxVersion=stable
+        IMAGE_TAG=stable
         ;;
         install)
         operation=install
@@ -252,6 +270,9 @@ function readParams {
         ;;
         update)
         operation=update
+        ;;
+        checkUpdate)
+        operation=checkUpdate
         ;;
         reinstall)
         operation=reinstall
@@ -277,11 +298,13 @@ function readParams {
 }
 
 function main {
+    source .env
 
     local install="Install: First time installing Panamax - Downloads CorsOS VM and installs latest Panamax version."
     local restart="Restart: Stops and Starts Panamax."
     local reinstall="Reinstall: Deletes your applications and CoreOS VM; reinstalls latest Panamax version."
-    local update="Update (not implemented): Retains your applications and updates Panamax to latest version."
+    local update="Update: Retains your applications and updates Panamax to latest version."
+    local checkUpdate="Check For updates to your Panamax Install."
     local stop="Stop: Stops Panamax"
     local start="Start: Starts Panamax"
     local uninstall="Uninstall: Deletes applications and CoreOS VM."
@@ -296,21 +319,23 @@ function main {
             restart) restartPanamax;;
             stop) stopPanamax;;
             start) restartPanamax;;
-            update) checkForUpdate "u";;
+            checkUpdate)checkForUpdate "u";;
+            update) updatePanamax;;
             uninstall) uninstallPanamax;;
             *) showHelp;;
         esac
 	
     else
         echo "Please select one of the following options: "
-        select operation in "$install" "$stop" "$start" "$restart" "$reinstall" "$update" "$uninstall"; do
+        select operation in "$install" "$stop" "$start" "$restart" "$reinstall" "$checkUpdate" "$update" "$uninstall"; do
         case $operation in
-            "$install") operation="install"; installPanamax; break;;
+            "$install") operation="install";  installPanamax; break;;
             "$reinstall") operation="reinstall"; installPanamax; break;;
             "$restart") operation="restart"; restartPanamax; break;;
             "$start") operation="start"; restartPanamax; break;;
             "$stop") operation="stop"; stopPanamax; break;;
-            "$update") operation="update"; checkForUpdate "u"; break;;
+            "$checkUpdate") operation="check_update"; checkForUpdate "u"; break;;
+            "$update") operation="update"; updatePanamax; break;;
             "$uninstall") operation="uninstall"; uninstallPanamax; break;;
         esac
         done
