Updating panamax to work with brew.

diff --git a/panamax b/panamax
--- a/panamax
+++ b/panamax
@@ -1,12 +1,15 @@
 #! /bin/bash
 
+
 PANAMAX_PORT_UI=8888
 PANAMAX_PORT_API=8889
-BASEBOX=coreos-beta
+BASEBOX=coreos-alpha
 IMAGE_TAG_DEFAULT=stable
 pmxUiTags="http://74.201.240.198:5000/v1/repositories/panamax-ui/tags"
 pmxApiTags="http://74.201.240.198:5000/v1/repositories/panamax-api/tags"
 setupUpdateUrl="http://63.128.180.11/installer/"
+CWD="${HOME}/.panamax/"
+env=$CWD/.env
 
 function displayLogo {
 tput clear
@@ -43,28 +46,12 @@ function checkPreReqs {
     echo ""
 }
 
-function getNextOpenPorts {
- HOST=127.0.0.1;
- if [[ "$PANAMAX_PORT_UI" == "" && "$PANAMAX_PORT_API" == "" ]]; then
-     for((port=8898;port<=9999;++port));do
-       if [[ "`netstat -an | grep $port`" == "" ]]; then
-          if [[ "$PANAMAX_PORT_UI" == "" ]]; then
-              PANAMAX_PORT_UI=$port
-          else
-             PANAMAX_PORT_API=$port
-             break
-          fi
-       fi;
-     done
- fi
-}
-
 function checkForSetupUpdate {
     if [[ "$checkedSetupForUpdates" != "1" || "$1" == "u" ]]; then
         checkedSetupForUpdates="1"
         updateAvailableForSetup="0"
-        if [[ -f .env ]]; then
-            source .env
+        if [[ -f $env ]]; then
+            source $env
             majVer=`echo $SETUP_VERSION | awk -F "." '{ print $1 }'`
             minVer=`echo $SETUP_VERSION | awk -F "." '{ print $2 }'`
             patVer=`echo $SETUP_VERSION | awk -F "." '{ print $3 }'`
@@ -91,8 +78,8 @@ function checkForPanamaxUpdate {
    if [[ "$checkedPmxForUpdates" != "1" || "$1" == "u" ]]; then
        checkedPmxForUpdates="1"
        updateAvailableForPmx="0"
-       if [[ -f .env ]]; then
-        source .env
+       if [[ -f $env ]]; then
+        source $env
         if [[ "$IMAGE_TAG" == "dev" ]]; then
             if [[ "$INSTALL_DATE" -le "` date -j -v-1d +%s`" ]]; then
                 echo "You are currently running a Dev version of Panamax which is updated nightly."
@@ -138,6 +125,10 @@ function getLatestTagApi {
     echo `curl -silent $pmxApiTags  | grep '"[0-9]\+.[0-9]\+.[0-9]\+"' | awk '{ gsub(/[",:]/,"")} 1' | awk '{ print $1}' | awk 'END{print}'`
 }
 
+function runVagrant {
+   cd $CWD && vagrant "$@"
+}
+
 function installPanamax {
     if [[ $# == 0 ]]; then
         echo ""
@@ -152,18 +143,25 @@ function installPanamax {
     redownload=${download:-N}
     IMAGE_TAG=${panamaxVersion:-${IMAGE_TAG:-$IMAGE_TAG_DEFAULT}}
 
-    echo export PANAMAX_PORT_UI=$panamaxPortUi > .env
-    echo export PANAMAX_PORT_API=$panamaxPortApi >> .env
-    echo export BASEBOX=$BASEBOX >> .env
-    echo export SETUP_VERSION=\"$(<.version)\" >> .env
-    echo export INSTALL_DATE=\"`date +%s`\" >> .env
+    echo export PANAMAX_PORT_UI=$panamaxPortUi > $env
+    echo export PANAMAX_PORT_API=$panamaxPortApi >> $env
+    echo export BASEBOX=$BASEBOX >> $env
+    echo export SETUP_VERSION=\"$(<$CWD\.version)\" >> $env
+    echo export INSTALL_DATE=\"`date +%s`\" >> $env
     if [[ "$IMAGE_TAG" == "stable" ]]; then
-        echo export INSTALL_TAG_UI=\"$(getLatestTagUi)\" >> .env
-        echo export INSTALL_TAG_API=\"$(getLatestTagApi)\" >> .env
+        echo export INSTALL_TAG_UI=\"$(getLatestTagUi)\" >> $env
+        echo export INSTALL_TAG_API=\"$(getLatestTagApi)\" >> $env
     fi
     setEnvVar "IMAGE_TAG" "$IMAGE_TAG"
     setEnvVar "OPERATION" "$operation"
-    source .env
+    source $env
+
+    if [ ! -d "$CWD" ]; then
+        mkdir -p $CWD
+        cp -Rf . $CWD > /dev/null
+    fi
+
+
 
     if [[  $operation == "reinstall" ]]; then
         echo ""
@@ -171,24 +169,24 @@ function installPanamax {
 	if [[ "$#" == "0" ]]; then
 	    read -p "Would you like to re-download coreos base box(N): " redownload
 	fi
-        vagrant destroy -f || { echo "VM Destroy failed. Exiting."; exit 1; }
+        runVagrant destroy -f || { echo "VM Destroy failed. Exiting."; exit 1; }
         if [[ $redownload == "Y" ]]; then
             vagrant box update --box $BASEBOX || { echo "Vagrant box remove failed. Exiting."; exit 1; }
         else
-        vagrant up || { echo "VM Creation failed. Exiting."; exit 1; }
+        runVagrant up || { echo "VM Creation failed. Exiting."; exit 1; }
         fi
     else
 	echo ""
 	echo "Creating a new vagrant machine"
-	vagrant up || { echo "VM Creation failed. Exiting."; exit 1; }
+	runVagrant up || { echo "VM Creation failed. Exiting."; exit 1; }
     fi
 
     openPanamax;
 }
 
 function setEnvVar {
-    echo $"`sed  "/$1/d" .env`" > .env
-    echo export $1=$2 >> .env
+    echo $"`sed  "/$1/d" $env`" > $env
+    echo export $1=$2 >> $env
 }
 
 function openPanamax {
@@ -208,8 +206,8 @@ function openPanamax {
 function restartPanamax {
     echo Restarting Panamax
     setEnvVar "OPERATION" "$operation"
-    source .env
-    vagrant reload || { echo >&2 "Restarting Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
+    source $env
+    runVagrant reload || { echo >&2 "Restarting Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
     openPanamax;
     echo Restart complete
 }
@@ -218,19 +216,19 @@ function restartPanamax {
 function stopPanamax {
     echo Stopping Panamax
     setEnvVar "OPERATION" "$operation"
-    source .env
-    vagrant halt || { echo >&2 "Stopping Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
+    source $env
+    runVagrant halt || { echo >&2 "Stopping Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
     echo Panamax stopped.
 }
 
 function updatePanamax {
     setEnvVar "OPERATION" "$operation"
     setEnvVar "IMAGE_TAG" "$IMAGE_TAG"
-    source .env
+    source $env
     checkForPanamaxUpdate
     if [[ $updateAvailableForPmx == "1" ]]; then
         echo Updating Panamax
-        vagrant reload --provision || { echo >&2 "Updating Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
+        runVagrant reload --provision || { echo >&2 "Updating Panamax seems to have failed. Please try again using the reinstall option."; exit 1; }
         openPanamax;
         echo Update Complete
     else
@@ -241,7 +239,7 @@ function uninstallPanamax {
   setEnvVar "OPERATION" "$operation"
   echo Uninstalling Panamax
   vagrant box remove $BASEBOX
-  vagrant destroy -f
+  runVagrant destroy -f
   echo Uninstall complete.
 }
 
@@ -307,7 +305,7 @@ function readParams {
 }
 
 function main {
-    source .env
+    source $env
     displayLogo
 
     local install="Init:  First time installing Panamax! - Downloads CoreOS VM and installs latest Panamax version."
@@ -324,8 +322,8 @@ function main {
     
     if [[ $# -gt 0 ]]; then
         case $operation in
-            install) getNextOpenPorts; installPanamax "$@" || { showHelp; exit 1; } ;;
-            reinstall) getNextOpenPorts; installPanamax "$@" || { showHelp; exit 1; } ;;
+            install)   installPanamax "$@" || { showHelp; exit 1; } ;;
+            reinstall)   installPanamax "$@" || { showHelp; exit 1; } ;;
             restart) restartPanamax;;
             stop) stopPanamax;;
             start) restartPanamax;;
